//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int maad { get; set; }
        public string tenad { get; set; }
        public string usernamead { get; set; }
        public string mkad { get; set; }
        public string emailad { get; set; }
    }
}
