//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laptrinhwebEntities1 : DbContext
    {
        public laptrinhwebEntities1()
            : base("name=laptrinhwebEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DANHMUC> DANHMUCs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TTHOADON> TTHOADONs { get; set; }

        internal void SupmitChange()
        {
            throw new NotImplementedException();
        }

        internal void SupmitChanges()
        {
            throw new NotImplementedException();
        }
    }
}
