//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.TTHOADONs = new HashSet<TTHOADON>();
        }
    
        public string maHD { get; set; }
        public Nullable<int> maND { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public string DC { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual ICollection<TTHOADON> TTHOADONs { get; set; }
    }
}
