//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.TTHOADONs = new HashSet<TTHOADON>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string giahientai { get; set; }
        public string mota { get; set; }
        public string xuatsu { get; set; }
        public string maDM { get; set; }
        public string hinh { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual ICollection<TTHOADON> TTHOADONs { get; set; }
    }
}
